version: '3.7'
services:
  jekyll:
    build: .
    command: bundle exec jekyll build
    entrypoint: ["bundle", "exec", "jekyll", "serve", "--watch" ,"--host=0.0.0.0"]
    ports:
      - 4000:4000
    volumes:
      - .:/app